# Generated by Django 5.2 on 2025-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry_areas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministryarea',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ministryarea',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ministryarea',
            name='slug',
            field=models.SlugField(default='ministry-slug', unique=True),
        ),
    ]
