# Generated by Django 5.2 on 2025-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Addition'), ('REMOVE', 'Removal'), ('ADJUST', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('previous_quantity', models.PositiveIntegerField(verbose_name='previous quantity')),
                ('new_quantity', models.PositiveIntegerField(verbose_name='new quantity')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inventory transaction',
                'verbose_name_plural': 'inventory transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='minimum quantity')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit value')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='acquisition date')),
                ('condition', models.CharField(blank=True, max_length=50, verbose_name='condition')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='storage location')),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True, verbose_name='barcode')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['name'],
            },
        ),
    ]
